// Generated by scripts/build-extension.mjs — do not edit. Run `npm run build:extension` after changing extension/.
export const EXTENSION_VERSION = "0.6.1";
export const EXTENSION_ZIP_URL = "/cuelara-extension-v0.6.1.zip";
