// Generated by scripts/build-extension.mjs — do not edit. Run `npm run build:extension` after changing extension/.
export const EXTENSION_VERSION = "1.0.0";
export const EXTENSION_ZIP_URL = "/cuelara-extension-v1.0.0.zip";
